### ISSUE TITLE
Updating vendor packages is tedious, should be automated

### ISSUE THREAD

**Issue by cprovencher** [mesosphere/dcos-e2e#733]
Updating packages in: https://github.com/mesosphere/dcos-e2e/tree/master/src/dcos_e2e/_vendor
should be automated. It's also not possible to simply copy the new folder over either because all the import paths are changed to relative paths using ../

@timaa2k Mentioned to me that this was done to avoid problems with --process-dependency-links with pip install. What I suggest is taking the same approach as in dcos-launch, which is instead of making the repo pip installable, making it into a Tox binary. With this method you'll be able to make your vendor packages proper python dependencies. The way we have it set up in dcos-launch right now: every merge to master runs a Tox build and publishes a binary pointed to by a download link in the repo's README.

**Comment by adamtheturtle** [comment]
@cprovencher I don't consider it tedious. We have a script `admin/update_vendored_packages.sh` which does it all. That is described [here, in the contributing documentation](http://dcos-e2e.readthedocs.io/en/latest/contributing.html#id11). A maintainer updates the SHAs, and then runs that script. Does that solve the issue that you worry about?

**Comment by adamtheturtle** [comment]
>  It's also not possible to simply copy the new folder over either because all the import paths are changed to relative paths using ../

That issue is solved by our scripts which use [`python-vendorize`](https://github.com/mwilliamson/python-vendorize) to change import paths.

**Comment by cprovencher** [comment]
Great docs you have there I will read them next time, thanks!
