### ISSUE TITLE
"make lint" fails locally, master branch

### ISSUE THREAD

**Issue by cprovencher** [mesosphere/dcos-e2e#777]
Warning, treated as error:
autodoc: failed to import class 'AWS' from module 'dcos_e2e.backends'; the following exception was raised:
cannot import name 'opentype'
Makefile:20: recipe for target 'linkcheck' failed
make[1]: *** [linkcheck] Error 2
make[1]: Leaving directory '/home/cprovencher/dcos-e2e/docs'
Makefile:78: recipe for target 'linkcheck' failed
make: *** [linkcheck] Error 2

Using: python 3.5
running: pip install --user --editable .[dev]
these warnings occurred, which may or may not be related to the issue:
dcos 0.6.1 has requirement PyJWT==1.4.2, but you'll have pyjwt 1.6.1 which is incompatible.
dcoscli 0.6.1 has requirement cryptography==2.0.2, but you'll have cryptography 2.2.2 which is incompatible.
pyasn1-modules 0.2.1 has requirement pyasn1<0.5.0,>=0.4.1, but you'll have pyasn1 0.1.9 which is incompatible.
boto3 1.7.7 has requirement botocore<1.11.0,>=1.10.7, but you'll have botocore 1.10.6 which is incompatible.

**Comment by adamtheturtle** [comment]
I think that this was a very temporary issue which has now been resolved with a `botocore` update. Please re-open if it happens again.
