### ISSUE TITLE
Cannot install dependencies and run make lint in virtual environment

### ISSUE THREAD

**Issue by cprovencher** [mesosphere/dcos-e2e#778]
When installing the dependencies using Python 3.6, pip 3.6 and running "pip install --user --editable .[dev]", inside a virtual environment, dulwich package cannot be installed:
dulwich error:
creating build/temp.linux-x86_64-3.6/dulwich
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -I/home/cprovencher/venv/include/python3.6m -c dulwich/_objects.c -o build/temp.linux-x86_64-3.6/dulwich/_objects.o
dulwich/_objects.c:21:20: fatal error: Python.h: No such file or directory
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

"make lint" then proceeds to make unwanted changes that result in CI failure.
"make lint" is also not currently configurable so it cannot skip directories or files such as "venv" virtual environment folder, which will also result in a make lint failure.

**Comment by adamtheturtle** [comment]
I'm hoping that this means just that we need to specify one of:

```
sudo apt-get install python3-dev
```

```
sudo yum install python35-devel
```

or

```
sudo yum install python36-devel
```


As I do not have this issue, please could you try the relevant one of those and let me know if it works for you. If so, I will add to the documentation.

**Comment by adamtheturtle** [comment]
I recreated this issue with:

```
$ docker run -it ubuntu /bin/bash
# apt update
# apt install -y python3 curl
# curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
# python3 get-pip.py
# pip install dulwich
```

And fixed it with:

```
# apt install -y gcc python3-dev
```

I will document this.
